# Generated by Django 3.2.3 on 2021-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
